### PR TITLE
securitycontext should not be cleared when it was not populated by we…

### LINKED ISSUE #8: security context cleared even if it was not populated by execution hook
When security context is present in SecurityContextHolder after [this](https://github.com/nextgearcapital/feign-hystrix-oauth2-spring-boot-starter/blob/master/src/main/java/com/nextgearcapital/feign/oauth2/autoconfigure/hystrix/SecurityContextRegistratorCommandHook.java#L28) and [this](https://github.com/nextgearcapital/feign-hystrix-oauth2-spring-boot-starter/blob/master/src/main/java/com/nextgearcapital/feign/oauth2/autoconfigure/hystrix/SecurityContextRegistratorCommandHook.java#L36) lines it will be removed what causes errors in web request. It would be better to distinguish if SecurityContextHolder was populated by execution hook or not.

### PR DESCRIPTION
**Pull request by bilak**
…b hook.

fixes #8

please would it be possible to release it to maven? thanks

### CODE REVIEW

**Comment by scheerer** [comment]
Thanks so much! We recently discovered that Spring already implements this for all of us via:

```xml        
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-oauth2</artifactId>
</dependency>
```

I think you will find replacing the usage of this library with the `org.springframework.cloud:spring-cloud-starter-oauth2` dependency will solve your problems.

**Comment by bilak** [comment]
Oh I didn't realised that this exists. Does it configure hystrix and feign like your project? I can't find the autoconfiguration for hystrix/feign.

**Comment by scheerer** [comment]
Yeah I don't see their auto configuration for it either. I actually in fact am having some problems with their version as well. In the meantime I'll merge this and get a new release out there.

**Comment by scheerer** [comment]
the 1.0.3 version should be making its way to Maven central soon... it should at least be there by tomorrow.

**Comment by bilak** [comment]
Thank you

**Pull request merged**
